### ISSUE TITLE
Incorrectly setting fixed height on add reviews div causing error

### ISSUE THREAD

**Issue by TobyDS** [london-codeworks-thesis/spot#20]
Using a fixed height, even with relative units, is dangerous; fixed height should rarely be used. Here, the div's contents will make it the correct height anyway. If you need to use a height, often you should only be setting ''min height'.

![localhost_3001_dashboard_add Overview (2024-05-08 10 24 33)](https://github.com/london-codeworks-thesis/spot/assets/33652695/7304c5bd-e275-40ea-9a0f-5fd7f02c1bd2)

**Comment by SunnyAnter** [comment]
done
